version: 2
jobs:
  test-clj:
    docker:
      - image: circleci/clojure:lein
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein test
  build:
    docker:
      - image: circleci/clojure:lein
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein cljsbuild once min
      - persist_to_workspace:
          root: resources
          paths:
            - public
  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: resources
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci@polymeris.dev"
            git config user.name "ci"
      - add_ssh_keys:
          fingerprints:
            - "43:34:cd:cc:e6:d4:8d:19:52:fa:5a:83:33:0e:59:cf"
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --dist resources/public

workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test-clj
      - build
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - test-clj
            - build
